library/book_library/urls.py
from django.urls import path

from . import views

app_name = 'book_library'
urlpatterns = [
    path('', views.index, name="index"),
    path('all_books', views.all_books, name="all_books"),
    path('wishlist', views.wishlist, name="wishlist"),
    path('finished_reading', views.finished_reading, name="finished_reading"),
    path('<int:book_id>/', views.detail, name='detail'),
    path('<int:book_id>/rate/', views.rate, name='rate'),
    path('<int:book_id>/change_status/', views.change_status, name='change_status'),
    path('add_book', views.add_book, name="add_book"),
    path('search_book', views.search_book, name="search_book"),
    # path('search_results', views.search_results, name="search_results"),
    path('author/<int:author_id>/', views.author_page, name='author_page'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('book_library/', include('book_library.urls')),
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico')))
]

library/book_library/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Publisher(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
class Book(models.Model):
    title = models.CharField(max_length=100, unique=True)
    subtitle = models.CharField(max_length=200, default='')

    author = models.ForeignKey(Author, on_delete=models.DO_NOTHING)

    publisher = models.ForeignKey(Publisher, on_delete=models.DO_NOTHING)
    publication_date = models.DateField()
    # pages = models.IntegerField(default=0)
    score = models.IntegerField(
        default=0,
        validators=[MaxValueValidator(5), MinValueValidator(0)]
    )

    read = models.BooleanField(default=0)
    on_wishlist = models.BooleanField(default=1)
    in_possession = models.BooleanField(default=0)
    reading =  models.BooleanField(default=0)
    
    date_added = models.DateField(auto_now_add=True)
    date_started_reading = models.DateField(null=True, blank=True)
    date_acquired = models.DateField(null=True, blank=True)
    date_read = models.DateField(null=True, blank=True)
    
    isbn = models.CharField(max_length=20, default=0, null=True)
    URL = models.URLField(max_length=200, default='#')
    
    # class Meta:
        # unique_together = ['title', 'EAN']
    
    def __str__(self):
        return self.title

    def __iter__(self):
        for field in self._meta.get_fields():
            value = getattr(self, field.name, None)
            yield (field.name, value)

            

library/book_library/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.db.models import Q

import datetime

import pdb

from .models import Book, Author, Publisher
from .bol_scrape import get_information

# Create your views here.


def index(request):
    book_list = Book.objects.order_by('-date_added')[:25]
    latest_wish_list = Book.objects.filter(on_wishlist=True).order_by('-date_added')[:10]
    
    latest_finished_list = Book.objects.filter(read=True).order_by('-date_read')[:10]

    context = {'book_list' : book_list,
               'wish_list' : latest_wish_list,
               'finished_list' : latest_finished_list,}
    
    return render(request, 'book_library/index.html', context)

def all_books(request):
    book_list = Book.objects.order_by('-publication_date')
    context = {'book_list' : book_list,}
    return render(request, 'book_library/all_books.html', context)

def wishlist(request):
    wishlist = Book.objects.filter(on_wishlist=True).order_by('-date_added')
    context = {'wishlist' : wishlist,}
    return render(request, 'book_library/wishlist.html', context)

def finished_reading(request):
    finished_list = Book.objects.filter(read=True).order_by('-date_added')
    context = {'finished_list' : finished_list,}
    return render(request, 'book_library/finished_reading.html', context)

def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if book.on_wishlist:
        status = 'On wishlist'
    elif book.read:
        status = 'Finished reading'
    elif book.in_possession:

        if book.reading:
            status = "Currently Reading"
        else:
            status = 'Acquired'


    context = {
        'book' : book,
        'author' : book.author,
        'fieldnames' : [f'{f.capitalize()} : {v}' for f, v in book.__iter__()],
        'score_range' : range(1,6),
        'status' : status

    }
    return render(request, 'book_library/detail.html', context)

def author_page(request, author_id):
    author = get_object_or_404(Author, pk=author_id)

    book_list = Book.objects.filter(author__id=author.id)
    
    print(book_list)
    context = {
        'author' : author,
        'book_list' : book_list,
    }
    
    return render(request, 'book_library/author_page.html', context)

def rate(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    given_score = request.POST['score']

    book.score = given_score
    book.save()
    
    return HttpResponseRedirect(reverse('book_library:detail', args=(book.id,)))

def change_status(request, book_id):
    book = get_object_or_404(Book, pk=book_id)


    new_status = request.POST.get('status')

    if new_status == 'On wishlist':
        book.on_wishlist = 1
        book.read = 0
        book.reading = 0
        book.in_possession = 0
    elif new_status == 'In possession':
        book.on_wishlist = 0
        book.in_possession = 1
        book.read = 0
        book.date_acquired = datetime.datetime.now()
    elif new_status == 'Read':
        book.on_wishlist = 0
        book.in_possession = 1
        book.reading = 0
        book.read = 1
        book.date_read = datetime.datetime.now()
    elif new_status == 'Currently reading':
        book.on_wishlist = 0
        book.in_possession = 1
        book.reading = 1
        book.read = 0
        book.date_started_reading = datetime.datetime.now()

    book.save()
    
    return HttpResponseRedirect(reverse('book_library:detail', args=(book.id,)))

def add_book(request):
    url = request.POST['add_book']

    information = get_information(url)

    try:
        book = get_object_or_404(Book, title=information['title'])
        return HttpResponseRedirect(reverse('book_library:index'))
    except:
        aut_str = information['author'].split()
        new_author = Author(first_name=aut_str[0], last_name=' '.join(aut_str[1:]))
        new_author.save()

        publisher = Publisher.objects.filter(name=information['publisher'])

        if not publisher:
            new_publisher = Publisher(name=information['publisher'])
            new_publisher.save()
            publisher = new_publisher
        else:
            publisher = publisher[0]
        
        new_book = Book(title=information['title'],
                        author=new_author,
                        subtitle=information['subtitle'],
                        publication_date=information['publication_date'],
                        publisher=publisher,
                        # pages=information['pages'],
                        isbn=information['isbn'],
                        URL=url,
                        date_added=datetime.datetime.now())

        new_book.save()    
        # new_book.authors.add(new_author)
        
        return HttpResponseRedirect(reverse('book_library:index'))



def search_book(request):
    query = request.GET['search_book']

    query_results = Book.objects.filter(
        Q(title__icontains=query) | Q(authors__first_name__icontains=query) | Q(authors__last_name__icontains=query))
    
    
    context = {
        'query': query,
        'query_results' : query_results,
    }
    
    return render(request, 'book_library/search_results.html', context)

library/book_library/templates/book_library/all_books.html
{% extends 'book_library/base.html' %}

{% block title %}All books{% endblock %}

{% block content %}
{% load static %}

<div class="row" style="margin-top: 1em;">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">All books ({{ book_list|length }})</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% if book_list %}
	  {% for book in book_list %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.authors.all|join:", " }} </small>
	    <br>

	  </a>
	  {% endfor %}
	  {% else %}
	  <p>No books are available.</p>
	  {% endif %}
	</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<!-- <!DOCTYPE html> -->
<!-- <html> -->
<!--   <head> -->
<!--     <meta charset="utf-8"> -->

<!--     <title>My Library</title> -->
<!--   </head> -->
<!--   <body> -->
<!--     {% if book_list %} -->
<!--     <ul> -->
<!--       {% for book in book_list %} -->
<!--       <li><a href="{% url 'book_library:detail' book.id  %}">{{ book.title }}</a></li> -->
<!--       {% endfor %} -->
<!--     </ul> -->
<!--     {% else %} -->
<!--     <p>No books are available.</p> -->
<!--     {% endif %} -->
<!--   </body> -->
<!-- </html> -->

library/book_library/templates/book_library/author_page.html
{% extends 'book_library/base.html' %}

{% block title %}{{ author.first_name }} {{ author.last_name }}{% endblock %}

{% block content %}
{% load static %}

<div class="row" style="margin-top: 1em;">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">{{ author.first_name }} {{ author.last_name }} ({{ book_list|length }})</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% if book_list %}
	  {% for book in book_list %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.authors.all|join:", " }} </small>
	    <br>

	  </a>
	  {% endfor %}
	  {% else %}
	  <p>No books are available.</p>
	  {% endif %}
	</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<!-- <!DOCTYPE html> -->
<!-- <html> -->
<!--   <head> -->
<!--     <meta charset="utf-8"> -->

<!--     <title>My Library</title> -->
<!--   </head> -->
<!--   <body> -->
<!--     {% if book_list %} -->
<!--     <ul> -->
<!--       {% for book in book_list %} -->
<!--       <li><a href="{% url 'book_library:detail' book.id  %}">{{ book.title }}</a></li> -->
<!--       {% endfor %} -->
<!--     </ul> -->
<!--     {% else %} -->
<!--     <p>No books are available.</p> -->
<!--     {% endif %} -->
<!--   </body> -->
<!-- </html> -->

library/book_library/templates/book_library/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block title %}{% endblock %}
    </title>
    
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">	
  <link rel="stylesheet" stype="text/css" href="{% static 'book_library/css/bootstrap.min.css' %}">
  <link rel="stylesheet" stype="text/css" href="{% static 'book_library/css/custom.css' %}">
  
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
</head>
<body>
  <div class="container">
  <div class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'book_library:index' %}">Berend's Book Library</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"></button>
  </div>
<div id="content", name="content", class="main">    
{% block content %}
{% endblock %}
</div>
</div>
</body>

</html>

library/book_library/templates/book_library/detail.html
{% extends 'book_library/base.html' %}

{% block title %}{{ book.title }}{% endblock %}


{% load static %}
{% block content %}

<div class="row" style="margin-top: 1em;">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">{{ book.title }} - {{ status }}</h3>
      </div>
      <div class="panel-body">
	<table class="table">
	  <tr>
	    <td>Title:</td>
	    <td>'{{ book.title }}'</td>
	  </tr>
	  <tr>
	    <td>Subtitle:</td>
	    <td>{{ book.subtitle }}</td>
	  </tr>
	  <tr>
	    <td>Author:</td>
	    <td><a href="{% url 'book_library:author_page' author.id %}">{{ book.author }}</a></td>
	  </tr>
	  <tr>
	    <td>Publication date:</td>
	    <td>{{ book.publication_date }}</td>
	  </tr>
	  <tr>
	    <td>Pages:</td>
	    <td>{{ book.pages }}</td>
	  </tr>
	  <tr>
	    <td>Publisher:</td>
	    <td>{{ book.publisher }}</td>
	  </tr>
	  <tr>
	    <td>EAN:</td>
	    <td>{{ book.EAN }}</td>
	  </tr>
	    <!-- {% if book %} -->
	    <!-- <ul> -->
	    <!--   {% for f in fieldnames %} -->
	    <!--   <li>{{ f }} </li> -->
	    <!--   {% endfor %} -->
	    <!-- </ul> -->
	    <!-- {% else %} -->
	    <!-- <p>No books are available.</p> -->
	    <!-- {% endif %} -->
	</table>
      </div>
    </div>
    <br>
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Status</h3>
      </div>
      <div class="panel-body">
	<table class="table">
	  <tbody>
	    <tr>
	      <td>Status:</td>
	      <td>{{ status }}</td>
	    </tr>
	    
	    {% ifnotequal book.score 0 %}
	    <tr>
	    <td>Rating:</td> <td>{{ book.score }}</td>
	    </tr>
	    {% endifnotequal %}
	    
	    <tr>
	      <td>Date added:</td>
	      <td>{{ book.date_added }}</td>
	    </tr>
	    
	    {% if book.date_acquired %}
	    <tr>
	      <td>Date acquired:</td>
	      <td>{{ book.date_acquired }}</td>
	    </tr>
	    {% endif %}
	    
	    {% if book.date_started_reading %}
	    <tr>
	      <td>Started reading on:</td>
	      <td>{{  book.date_started_reading }}</td>
	    </tr>
	    {% endif %}
	    
	    {% if book.date_read %}
	    <tr>
	      <td>Finished reading on:</td>
	      <td>{{ book.date_read }}</td>
	    </tr>
	    {% endif %}
	    
	  </tbody>
	</table>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title"></h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  <div class="list-group-item clearfixb">
	    {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="50%">
	      {% endwith %}
	  </div>
	</div>
      </div>
    </div>
        <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Rating</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  <div class="list-group-item clearfix">
	    <form action="{% url 'book_library:rate' book.id %}" method="post">
	      {% csrf_token %}
	      {% for i in score_range %}
	      <div class="form-check form-check-inline col-auto">
		<input type="radio" name="score" id="score{{ i }}" value="{{ i }}" class="form-check-input">
		<label for="score{{ i }}" class="form-check-label">
		  {{ i  }}
		</label>
	      </div>
	      {% endfor %}
	      <input type="submit" value="Vote" class="float-right">
	    </form>
	  </div>
	</div>	
      </div>
    </div>
    <br>
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Status</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  <div class="list-group-item clearfix">
	    <form action="{% url 'book_library:change_status' book.id %}" method="post">

	      {% csrf_token %}
	      <div class="form-check">
		<input type="radio" name="status" id="statuswishlist" value="On wishlist" class="form-check-input">
		<label for="statuswishlist" class="form-check-label">
		  On wishlist
		</label>
	      </div>
	      <div class="form-check">
		<input type="radio" name="status" id="statuspossesion" value="In possession" class="form-check-input">
		<label for="statuspossesion" class="form-check-label">
		  In possession
		</label>
	      </div>
	      <div class="form-check">
		<input type="radio" name="status" id="statusreading" value="Currently reading" class="form-check-input">
		<label for="statusreading" class="form-check-label">
		  Currently Reading
		</label>
	      </div>
	      <div class="form-check">
		<input type="radio" name="status" id="statusread" value="Read" class="form-check-input">
		<label for="statusread" class="form-check-label">
		  Read
		</label>
	      </div>

	      <input type="submit" value="Change">
	    </form>
	  </div>
	</div>
      </div>
    </div>
  </div>
{% endblock %}

library/book_library/templates/book_library/finished_reading.html
{% extends 'book_library/base.html' %}

{% block title %}Finished reading{% endblock %}

{% block content %}
{% load static %}

<div class="row" style="margin-top: 1em;">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Finished reading ({{ finished_list|length }})</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% if finished_list %}
	  {% for book in finished_list %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.authors.all|join:", " }} </small>
	    <br>

	  </a>
	  {% endfor %}
	  {% else %}
	  <p>No books are available.</p>
	  {% endif %}
	</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<!-- <!DOCTYPE html> -->
<!-- <html> -->
<!--   <head> -->
<!--     <meta charset="utf-8"> -->

<!--     <title>My Library</title> -->
<!--   </head> -->
<!--   <body> -->
<!--     {% if book_list %} -->
<!--     <ul> -->
<!--       {% for book in book_list %} -->
<!--       <li><a href="{% url 'book_library:detail' book.id  %}">{{ book.title }}</a></li> -->
<!--       {% endfor %} -->
<!--     </ul> -->
<!--     {% else %} -->
<!--     <p>No books are available.</p> -->
<!--     {% endif %} -->
<!--   </body> -->
<!-- </html> -->

library/book_library/templates/book_library/index.html
{% extends 'book_library/base.html' %}

{% block title %}Berend's Boeken{% endblock %}

{% block content %}
{% load static %}

<div class="row" style="margin-top: 1em;">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Add Book</h3>
      </div>
      <div class="panel-body">
	<form action="{% url 'book_library:add_book' %}" method="POST">
	  {% csrf_token %}
	  <input class="form-control" type="text" name="add_book" id="add_book" placeholder="Add book by Bol.com URL">
	  <br>
	  <!-- <button class="btn btn-default float-right" type="submit">Add</button> -->
	</form>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
	<a href="{% url 'book_library:all_books' %}"><h3 class="panel-title">Books ({{ book_list|length }})</h3></a>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% if book_list %}
	  {% for book in book_list %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.author }} </small>
	    <br>

	  </a>
	  {% endfor %}
	  {% else %}
	  <p>No books are available.</p>
	  {% endif %}
	</div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Search books</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  <form action="{% url 'book_library:search_book' %}" method="GET">
	  {% csrf_token %}
	  <input class="form-control" type="text" name="search_book" id="search_book" placeholder="Search in library">
	  <br>
	  <!-- <button class="btn btn-default float-right" type="submit">Add</button> -->
	</form>
	</div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">Currently Reading</h3>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% for book in book_list %}
	  {% if book.reading %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.author }} </small>
	    <br>
	  </a>
	  {% endif %}
	  {% endfor %}
	</div>
      </div>
    </div>
    <br>
    <div class="panel panel-default">
      <div class="panel-heading">
	<a href="{% url 'book_library:wishlist' %}"><h3 class="panel-title">New on wishlist</h3></a>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% for book in wish_list %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.author }} </small>
	    <br>
	  </a>
	  {% endfor %}
	</div>
      </div>
    </div>
    <br>
    <div class="panel panel-default">
      <div class="panel-heading">
	<a href="{% url 'book_library:finished_reading' %}"><h3 class="panel-title">Just finished reading</h3></a>
      </div>
      <div class="panel-body">
	<div class="list-group">
	  {% for book in finished_list %}
	  <a class="list-group-item clearfix" href="{% url 'book_library:detail' book.id  %}">
	    <div class="float-right">
	      {% with 'book_library/thumbnails/'|add:book.title|add:'.jpg' as img_static %}
	      <img class="img-rounded img-responsive" alt="Book thumbnail" style="margin-left: 12px;" src="{% static img_static %}"  width="40px">
	      {% endwith %}
	    </div>
	    <small>{{ book.date_added }}</small>
	    <br>
	    '{{ book.title }}'
	    <br>
	    <small> {{ book.author }} </small>
	    <br>
	    <small>Rating: {{ book.score }}/5 </small>
	  </a>
	  {% endfor %}
	</div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<!-- <!DOCTYPE html> -->
<!-- <html> -->
<!--   <head> -->
<!--     <meta charset="utf-8"> -->

<!--     <title>My Library</title> -->
<!--   </head> -->
<!--   <body> -->
<!--     {% if book_list %} -->
<!--     <ul> -->
<!--       {% for book in book_list %} -->
<!--       <li><a href="{% url 'book_library:detail' book.id  %}">{{ book.title }}</a></li> -->
<!--       {% endfor %} -->
<!--     </ul> -->
<!--     {% else %} -->
<!--     <p>No books are available.</p> -->
<!--     {% endif %} -->
<!--   </body> -->
<!-- </html> -->